<?php use Amderbar\Lib\Utils\HtmlUtil as Html; ?>
<?php use Amderbar\Lib\Utils\FileUtil as File; ?>
<?php use Amderbar\Lib\View; ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="<?=Html::csrfToken()?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/common.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/fonts.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/editor_area.css')?>">
    <title><?=APP_NAME?></title>
</head>
<body>
    <main id="app">
        <?php foreach ($tbl_tmpls as $tmpl_name) { ?>
            <?=Html::startForm(APP_ROOT . '/editor/data/update', null, 'POST', [
                'id' => 'table-form',
                'v-show' => "true || selected_template == '" . Html::escape($tmpl_name) . "'",
                'v-cloak' => true,
            ]) ?>
                <?=Html::hidden('pid', $proj_id) ?>
                <?=Html::hidden('tab', $tab_id) ?>
                <data-editor-<?=$tmpl_name?>
                    :tbl-meta="<?=Html::escape(json_encode($tbl_data['meta']))?>"
                    :tbl-data="<?=Html::escape(json_encode($tbl_data['data']))?>"
                ></data-editor-<?=$tmpl_name?>>
            <?=Html::endForm()?>
        <?php } ?>
    </main>

    <!-- Scripts -->
    <script src="<?=File::addFilemtime(APP_ROOT . '/js/manifest.js')?>"></script>
    <script src="<?=File::addFilemtime(APP_ROOT . '/js/vendor.js')?>"></script>
    <script src="<?=File::addFilemtime(APP_ROOT . '/js/editorApp.js')?>"></script>
</body>
</html>
