<?php use Amderbar\Lib\Utils\HtmlUtil as Html; ?>
<?php use Amderbar\Lib\Utils\FileUtil as File; ?>
<?php use Amderbar\Lib\View; ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="<?=Html::csrfToken()?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/common.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/fonts.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/editor_area.css')?>">
    <title><?=APP_NAME?></title>
</head>
<body>
    <?=Html::startForm(APP_ROOT . '/editor/data/modify', null, 'POST', ['id' => 'table-form']) ?>
    <?=Html::hidden('pid', $proj_id) ?>
    <?=Html::hidden('tab', $tab_id) ?>
    <main>

    <?php /*######## 表示テンプレートに置き換え ｺｺｶﾗ ########*/?>

    <?php View::include($tbl_tmpl, ['REQ_SCOPE' => $REQ_SCOPE]);?>

    <?php /*######## 表示テンプレートに置き換え ｺｺﾏﾃﾞ ########*/?>
    </main>

    <?=Html::endForm()?>
</body>

<?php View::yield('script');?>
<?php View::include(File::fullPath(VIEW_ROOT . '/vue_components.phtml'));?>

<script type="text/javascript">
    <?php /* 画面全体の動作を司るVueインスタンス */ ?>
    var test = new Vue({
        el: '#table-form',
        data: {
            column_names: <?=json_encode($tbl_data['col_name'])?>,
            column_config: <?=json_encode($tbl_data['form'])?>,
            tbl_data: <?=json_encode($tbl_data['data'])?>,
            default_data: <?=json_encode($tbl_data['default'])?>,
            modified_form: []
        },
        methods: {
            change: function (new_val, key_name, row_id) {
                Vue.set(this.tbl_data[row_id], key_name, new_val);
                var form_name = key_name + '[' + row_id + ']';
                if (this.modified_form.indexOf(form_name) < 0) {
                    this.modified_form.push(form_name);
                }
            },
            push: function (new_row) {
                var row_id = this.tbl_data.length;
                for (let name in new_row) {
                    this.modified_form.push(name + '[' + row_id + ']');
                }
                this.tbl_data.push(new_row);
            }
        }
    });
</script>
</html>
