<?php use Amderbar\Lib\Utils\HtmlUtil as Html; ?>
<?php use Amderbar\Lib\Utils\FileUtil as File; ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="<?=Html::csrfToken()?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/common.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/fonts.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime(APP_ROOT . '/css/main_panel.css')?>">
    <title><?=APP_NAME?></title>
</head>
<body>
    <div id="app" class="container">
        <side-nav ref="sideNav"
            :proj-list="<?=Html::escape(json_encode($proj_list ?? []));?>"
            :tbl-list="<?=Html::escape(json_encode($tbl_list ?? []));?>"
            :focus="<?=Html::escape($focus_pid ?? 0);?>"
        ></side-nav>
        <toggle-button
            id="toggle-menu"
            @show="$refs.sideNav.$emit('show')"
            @hide="$refs.sideNav.$emit('hide')"
            v-cloak
        ></toggle-button>
        <main-panel
            :tbl-list="<?=Html::escape(json_encode($tbl_list ?? []));?>"
            :pid="<?=Html::escape($focus_pid ?? 0);?>"
            :tbl="<?=Html::escape($focus_tbl ?? 0);?>"
        ></main-panel>
    </div>

    <!-- Scripts -->
    <script src="js/manifest.js"></script>
    <script src="js/vendor.js"></script>
    <script src="js/app.js"></script>
</body>
</html>
