<?php use Amderbar\Lib\Utils\HtmlUtil as Html; ?>
<?php use Amderbar\Lib\Utils\FileUtil as File; ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="<?=Html::csrfToken()?>">
    <!-- Styles -->
    <link href="css/app.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime('css/common.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime('css/fonts.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=File::addFilemtime('css/index.css')?>">
    <title><?=APP_NAME?></title>
</head>
<body>
    <header id="app" class="with-btns">
        <ul id="system_menu" class="menu">
            <?php foreach ([
                    'ファイル',
                    '編集',
                    '検索',
                    'ツール',
                    '設定',
                    'ウィンドウ',
                    'ヘルプ'
            ] as $link_txt) { ?>
                <li><?= Html::link($link_txt, 'javascript:void(0);', [], ['class' => 'btn']) ?></li>
            <?php } ?>
        </ul>
    </header>

    <iframe id="main" name="main" src="main<?= isset($proj_id) ? '?pid='.$proj_id : '' ?>" scrolling="no" frameborder="no"></iframe>
    <!-- <div id="app">
        <example-component></example-component>
    </div> -->

    <footer><strong id="top-title"><?=APP_NAME?></strong> <?=VERSION?></footer>

    <!-- Scripts -->
    <script src="js/manifest.js"></script>
    <script src="js/vendor.js"></script>
    <script src="js/app.js"></script>
</body>
</html>
